# ------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# ------------------------------------------------------------

- name: Install Sparks
  hosts: all
  tasks:
    - include_vars: spark_sql_settings.yml
    - name: Clean old installation if exsits
      file:
        path: "{{ spark_base }}"
        state: absent
    - name: Download Spark
      get_url:
        url: https://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.7.tgz
        dest: "{{ home_dir }}/spark.tgz"
    - name: Unzip Spark
      unarchive:
        src: "{{ home_dir }}/spark.tgz"
        dest: "{{ home_dir }}"
        remote_src: yes
    - name: Make configuration file
      shell: "cp {{ spark_base }}/conf/spark-env.sh.template {{ spark_base }}/conf/spark-env.sh"
    - name: Add memory option
      shell: echo "SPARK_WORKER_MEMORY={{ spark_memory }}m" >> {{ spark_base }}/conf/spark-env.sh
    - name: Remove install package
      file:
        state: absent
        path: "{{ home_dir }}/spark.tgz"